version: 0.2

phases:
  build:
    commands:
      - apt-get update -y
  post_build:
    commands:
      - aws s3 rm s3://planetvitals.com --recursive
      - aws s3 sync . s3://planetvitals.com/ 
      - aws cloudfront create-invalidation --distribution-id E3VICLJ9EAARCL --paths '/*'
#artifacts:
#  files:
#    - ./*
